site_name: Tensorizer
docs_dir: docs
theme:
  name: material # pip install mkdocs-material
  palette:
    primary: blue
    accent: blue
  logo: https://github.com/coreweave/tensorizer/assets/24918963/82f6afff-c31f-4969-9da4-c4b36368df35
  favicon: https://github.com/coreweave/tensorizer/assets/24918963/26efe75f-1282-4bf6-86f8-acfa6a4fbfcb
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # Required exception to allow Mermaid to function:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search # must declare search, because defining any plugins overrides the default list
  - mermaid2 # pip install mkdocs-mermaid2-plugin
  - literate-nav: # pip install mkdocs-literate-nav
      nav_file: SUMMARY.md
  - section-index: # pip install mkdocs-section-index
  - gen-files:
      scripts:
      - docs/scripts/mkdocs_gen_ref.py
  - mkdocstrings: # pip install mkdocstrings
      handlers:
        python:
          options: # These need review by ML team: (https://mkdocstrings.github.io/python/usage/configuration/general/)
            allow_inspection: true
            show_bases: true
            show_source: false
            # preload_modules: # See https://mkdocstrings.github.io/python/usage/configuration/general/#preload_modules
            #   - some_module_foo
            find_stubs_package: false
            heading_level: 2
            load_external_modules: true
            group_by_category: true
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: false
              allow_section_blank_lines: true
              returns_multiple_items: false
            docstring_section_style: spacy
            inherited_members: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_root_members_full_path: false
            show_object_full_path: false
            show_signature_annotations: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
            docstring_style: google

repo_url: https://github.com/coreweave/tensorizer

nav:
  - index.md
  - encryption.md
  - Architecture:
      - architecture/index.md
  - Code Reference: reference/
  - How To:
      - how-to/index.md
      - Advanced Topics:
          - how-to/index-advanced-topics.md
