site_name: Tensorizer
docs_dir: docs
theme:
  name: material # pip install mkdocs-material
  palette:
    primary: blue
    accent: blue
  logo: https://github.com/coreweave/tensorizer/assets/24918963/82f6afff-c31f-4969-9da4-c4b36368df35
  favicon: https://github.com/coreweave/tensorizer/assets/24918963/26efe75f-1282-4bf6-86f8-acfa6a4fbfcb
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # Required exception to allow Mermaid to function:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search # must declare search, because defining any plugins overrides the default list
  - mermaid2 # pip install mkdocs-mermaid2-plugin

# repo_url: https://github.com/coreweave/tensorizer

nav:
  - index.md
  - Architecture:
      - architecture/index.md

  - How To:
      - how-to/index.md
      - Advanced Topics:
          - how-to/index-advanced-topics.md

  - Reference:
      - reference/index.md
